services:
  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: 2gb
    ports:
      - "4444:4444"

  tests:
    build: .
    depends_on:
      - selenium
    environment:
      TEST_ENV: dev
      RUN_IN_DOCKER: "true"
      HEADLESS: "true"
    volumes:
      - ./allure-results:/app/allure-results
      - ./screenshots:/app/screenshots
